#include "sysClockConfig.h"
#include "TIM5setUp.h"

void configureTIM5(void){
	
	RCC->APB1ENR |= (1 << 3);   //ENABLE TIM5 PERIPHERAL CLOCK
	
	TIM5->PSC = 79;     //SET TIM5 FREQUENCY TO 1 MHZ (80000000/(79+1)) USING PRESCALER
	
	//TODO ADD NEW TIMER FOR MPU6050 SENSOR, SET BACK TIM5 RESET FREQ TO 200HZ
	TIM5->ARR = (uint32_t)300000;   //SET COUNTER RESET TIME
	
	//TIM5->CNT = 0;    //SET TIM5 COUNTER TO 0
	
	TIM5->DIER |= TIM_DIER_UIE;   //(1 << 0) ENABLE TIM2 INTERRUPT
	
	TIM5->SR &= ~TIM_SR_UIF;  //CLEAR TIM5 INTERRUPT STATUS
	
	NVIC_EnableIRQ(TIM5_IRQn);  //ENABLE GLOBAL NVIC INTERRUPTS FOR TIM5
	
	TIM5->CR1 = TIM_CR1_CEN;  // |= (1 << 0);  //ENABLE COUNTER FOR TIM5
}